export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';

export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const SET_ALL_QUESTIONS = 'SET_ALL_QUESTIONS';

export const UPDATE_QUESTION_AND_USERS = 'UPDATE_QUESTION_AND_USERS';
export const ADD_QUESTION_TO_ALL_QUESTIONS = 'ADD_QUESTION_TO_ALL_QUESTIONS';