export const LOGIN_USER = 'LOGIN_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_QUESTION_TO_USER_ANSWERS = 'ADD_QUESTION_TO_USER_ANSWERS';
export const ADD_QUESTION_TO_USER_QUESTIONS = 'ADD_QUESTION_TO_USER_QUESTIONS';